Repository Harbour-Enterprises/SuperDoc, pull requests merged in 2025-09, with the labels that each got.

#835 IDE-15 - fix: closing dropdown after clicking again
  packages/super-editor/src/components/toolbar/ButtonGroup.vue
Labels: Ready for review

#855 Fix: list outdent and lint
  packages/ooxml-inspector/src/children/cli.js
  packages/super-editor/src/core/commands/backspaceNextToList.js
  packages/super-editor/src/core/commands/decreaseListIndent.js
  packages/super-editor/src/core/commands/decreaseListIndent.test.js
  packages/super-editor/src/core/commands/toggleList.js
Labels: Ready for review

#843 fix(internal): remove pdfjs from build
  package-lock.json
  packages/superdoc/package.json
  packages/superdoc/postcss.config.cjs
  packages/superdoc/src/SuperDoc.vue
  packages/superdoc/src/components/PdfViewer/PdfViewer.vue
  packages/superdoc/src/components/PdfViewer/helpers/pdfjs-worker.js
  packages/superdoc/src/components/PdfViewer/helpers/read-file.js
  packages/superdoc/src/components/PdfViewer/pdf/pdf-adapter.js
  packages/superdoc/src/components/PdfViewer/pdf/pdf-viewer.css
  packages/superdoc/src/components/PdfViewer/pdfjs.js
  packages/superdoc/src/components/PdfViewer/worker.js
  packages/superdoc/src/core/SuperDoc.js
  packages/superdoc/src/dev/components/SuperdocDev.vue
  packages/superdoc/vite.config.js
  packages/superdoc/vite.config.umd.js
Labels: Ready for review

#860 fix: imports encoded in utf-16 break DocxZipper
  packages/super-editor/src/core/DocxZipper.js
  packages/super-editor/src/core/DocxZipper.test.js
  packages/super-editor/src/core/encoding-helpers.js
  packages/super-editor/src/core/encoding-helpers.test.js
Labels: Ready for review

#868 feat: add custom toolbar button example (HAR-10436)
  examples/customized-toolbar-example/README.md
  examples/customized-toolbar-example/demo-config.json
  examples/customized-toolbar-example/demo-thumbnail.png
  examples/customized-toolbar-example/demo-video.mp4
  examples/customized-toolbar-example/index.html
  examples/customized-toolbar-example/package.json
  examples/customized-toolbar-example/src/icon_cat.svg
  examples/customized-toolbar-example/src/main.js
  examples/customized-toolbar-example/src/style.css
  examples/customized-toolbar-example/vite.config.js
Labels: Ready for review

#869 fix: highlight selected value in font dropdowns
  packages/super-editor/src/components/toolbar/ButtonGroup.vue
  packages/super-editor/src/components/toolbar/constants.js
  packages/super-editor/src/components/toolbar/defaultItems.js
Labels: Ready for review

#876 Prepare for node translator (import/export upgrades), OxmlNode
  packages/super-editor/src/core/Node.js
  packages/super-editor/src/core/OxmlNode.js
  packages/super-editor/src/core/Schema.js
  packages/super-editor/src/core/index.js
  packages/super-editor/src/core/super-converter/SuperConverter.js
  packages/super-editor/src/core/super-converter/v2/handlers/index.js
  packages/super-editor/src/core/super-converter/v2/handlers/registry/handler-registry.js
  packages/super-editor/src/core/super-converter/v2/handlers/registry/handler-registry.test.js
  packages/super-editor/src/core/super-converter/v2/handlers/registry/index.js
  packages/super-editor/src/core/super-converter/v2/handlers/registry/logger.js
  packages/super-editor/src/core/super-converter/v2/handlers/registry/logger.test.js
  packages/super-editor/src/core/types/index.js
  packages/super-editor/vite.config.js
Labels: Ready for review

#874 fix: inserting html with heading tags does not render as expected (HAR-10430)
  package.json
  packages/super-editor/src/core/commands/insertContentAt.js
  packages/super-editor/src/core/commands/insertContentAt.test.js
  packages/super-editor/src/extensions/heading/heading.js
  packages/superdoc/src/assets/styles/layout/global.css
Labels: Ready for review

#878 fix: splitListItem if there are images or other atom nodes in list item, fix tests
  packages/super-editor/src/core/commands/list-helpers/test-helpers.js
  packages/super-editor/src/core/commands/splitListItem.js
  packages/super-editor/src/core/commands/splitListItem.test.js
  packages/super-editor/src/core/commands/toggleList.test.js
Labels: Ready for review

#880 fix: add processing for line-height defined in px
  packages/super-editor/src/core/super-converter/exporter.js
Labels: Ready for review

#888 fix: insertContentAt for html
  packages/super-editor/src/core/commands/insertContentAt.js
  packages/super-editor/src/core/commands/insertContentAt.test.js
Labels: Ready for review

#882 fix: list numbering
  packages/super-editor/src/core/helpers/orderedListUtils.js
  packages/super-editor/src/core/helpers/orderedListUtils.test.js
  packages/super-editor/src/core/super-converter/v2/importer/listImporter.js
Labels: Ready for review

#905 fix: retain page break when exporting hardBreak
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.test.js
Labels: codex

#910 feat: support additional tab attributes
  packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-leader.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-position.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tab/tab-translator.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tab/tab-translator.test.js
  packages/super-editor/src/extensions/tab/tab.js
Labels: codex

#901 feat: remove the heading node from superdoc
  packages/super-editor/src/extensions/heading/heading.js
  packages/super-editor/src/extensions/heading/heading.test.js
  packages/super-editor/src/extensions/linked-styles/helpers.js
  packages/super-editor/src/extensions/linked-styles/linked-styles.js
  packages/super-editor/src/extensions/linked-styles/linked-styles.test.js
  packages/super-editor/src/extensions/paragraph/paragraph.js
  packages/super-editor/src/extensions/paragraph/paragraph.test.js
Labels: Ready for review, Changes requested

#920 Import/export v3
  package-lock.json
  packages/super-editor/src/core/super-converter/exporter.js
  packages/super-editor/src/core/super-converter/v2/handlers/index.js
  packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js
  packages/super-editor/src/core/super-converter/v2/importer/lineBreakImporter.js
  packages/super-editor/src/core/super-converter/v2/importer/types/index.js
  packages/super-editor/src/core/super-converter/v2/types/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/types/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/attributes/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/attributes/w-clear.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/attributes/w-clear.test.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/attributes/w-line-break-type.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/attributes/w-line-break-type.test.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.test.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/br/index.js
  packages/super-editor/src/core/super-converter/v3/node-translator/index.js
  packages/super-editor/src/core/super-converter/v3/node-translator/node-translator.js
  packages/super-editor/src/extensions/line-break/line-break.js
  packages/super-editor/src/index.js
  packages/super-editor/src/tests/import/lineBreakImporter.test.js
  packages/superdoc/src/index.js
Labels: Ready for review

#929 refactor: update table cell import/export
  packages/super-editor/src/core/super-converter/exporter.js
  packages/super-editor/src/core/super-converter/v2/importer/tableImporter.js
  packages/super-editor/src/core/super-converter/v2/importer/types/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/legacy-handle-table-cell-node.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/legacy-handle-table-cell-node.test.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/translate-table-cell.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/translate-table-cell.test.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/index.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/tc-translator.js
  packages/super-editor/src/core/super-converter/v3/handlers/w/tc/tc-translator.test.js
Labels: Ready for review

#933 chore: add super editor coverage config
  package-lock.json
  package.json
  packages/super-editor/vite.config.js
Labels: Ready for review

#963 fix: emit editor exception on import/export errors
  packages/super-editor/src/components/SuperEditor.vue
  packages/super-editor/src/components/toolbar/super-toolbar.js
  packages/super-editor/src/core/Editor.js
  packages/super-editor/src/core/super-converter/SuperConverter.js
  packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js
  packages/super-editor/src/extensions/image/imageHelpers/startImageUpload.js
  packages/superdoc/src/core/SuperDoc.js
Labels: Ready for review

#978 fix: ul lists importing as ol
  packages/super-editor/src/core/Editor.js
  packages/super-editor/src/core/helpers/htmlSanitizer.js
  packages/super-editor/src/core/helpers/list-numbering-helpers.js
  packages/super-editor/src/core/helpers/list-numbering-helpers.test.js
Labels: Ready for review

#979 🔄 Sync: fix: ul lists importing as ol (#978)
  packages/super-editor/src/core/Editor.js
  packages/super-editor/src/core/helpers/htmlSanitizer.js
  packages/super-editor/src/core/helpers/list-numbering-helpers.js
  packages/super-editor/src/core/helpers/list-numbering-helpers.test.js
Labels: patch-sync

#1002 fix: headless mode crash
  packages/super-editor/src/core/helpers/htmlSanitizer.js
Labels: Ready for review

#1036 fix: do not track the annotation deletion on table generation
  packages/super-editor/src/core/helpers/annotator.js
  packages/super-editor/src/extensions/field-annotation/fieldAnnotationHelpers/findRemovedFieldAnnotations.js
Labels: Ready for review

#1045 fix: tracked changes don't have corresponding comments
  packages/super-editor/src/extensions/comment/comments-plugin.js
  packages/superdoc/src/SuperDoc.test.js
  packages/superdoc/src/SuperDoc.vue
  packages/superdoc/src/components/CommentsLayer/CommentDialog.test.js
  packages/superdoc/src/components/CommentsLayer/CommentDialog.vue
  packages/superdoc/src/helpers/group-changes.js
  packages/superdoc/src/stores/comments-store.js
  packages/superdoc/src/tests/helpers/group-changes.test.js
Labels: Ready for review
