Repository Harbour-Enterprises/SuperDoc, pull requests merged in 2025-10, with the labels that each got.

#1052 fix: instrtext bug with unhandled angled brackets (#1051)
  packages/super-editor/src/core/super-converter/exporter.js
  packages/super-editor/src/tests/data/instrtext-angled-brackets-bug.docx
  packages/super-editor/src/tests/export/docxExporter.test.js
  packages/super-editor/src/tests/export/fieldCodesExport.test.js
Labels: patch-sync

#1057 fix: structured content style with image
  packages/super-editor/src/assets/styles/extensions/structured-content.css
Labels: Ready for review

#1071 🔄 Sync: fix: preserve trailing spaces when inject html (#1070) * fix: preserve trailing spaces when inject html * fix: update code after rebase
  packages/super-editor/src/core/helpers/htmlSanitizer.js
Labels: patch-sync

#814 refactor: update document version handling and add SuperDoc ID [SD-428]
  packages/super-editor/src/core/Editor.js
  packages/super-editor/src/core/super-converter/SuperConverter.js
  packages/super-editor/src/core/super-converter/SuperConverter.test.js
  packages/super-editor/src/core/super-converter/exporter-docx-defs.js
  packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js
  packages/super-editor/src/tests/import/docxImporter.test.js
  shared/common/Telemetry.js
Labels: Changes requested
